In [3]:
import numpy as np

In [4]:
a=[1,2,3]

In [5]:
print(a)

[1, 2, 3]


In [6]:
#converting list to array
b=np.array(a)

In [7]:
print(b)

[1 2 3]


In [8]:
#sorting
print(b[1:3])

[2 3]


In [9]:
m=[1,2,]
n=[2,3,]
o=[3,4,]

In [10]:
#2D array
x=np.array([m,n,o])

In [11]:
print(x)

[[1 2]
 [2 3]
 [3 4]]


In [12]:
#finding shape of array
x.shape

(3, 2)

In [13]:
#changing shape of array rows to colums
x.reshape(2,3)

array([[1, 2, 2],
       [3, 3, 4]])

In [14]:
#random numbers
l=np.arange(1,19)

In [15]:
print(l)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [16]:
#changing 1D array to 2D array using reshape 
i=l.reshape(3,6)
print(i)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [17]:
#accessing elements using indexing
i[2,5]

np.int64(18)

In [18]:
#to know type of array
print(type(i))

<class 'numpy.ndarray'>


In [19]:
arr=np.array([[1,2,3],[2,3,4]])
print(arr)

[[1 2 3]
 [2 3 4]]


In [20]:
#sorting 2D array
print(arr[0:2,1:3])

[[2 3]
 [3 4]]


In [21]:
#reshapping 2D array
arr.reshape(3,2)

array([[1, 2],
       [3, 2],
       [3, 4]])

In [22]:
print(i)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [23]:
print(i[2:,:5])

[[13 14 15 16 17]]


In [24]:
print(i)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [25]:
i.shape

(3, 6)

In [26]:
i.reshape(6,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [27]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.random.randint(2,33,6).reshape(3,2)

array([[10, 11],
       [14, 11],
       [13,  5]], dtype=int32)

In [30]:
np.random.randn(3,3)

array([[ 0.06338197, -2.1805468 , -1.03134132],
       [-0.51979727, -1.57403384, -0.27650388],
       [-0.84481387,  0.86769003, -1.24708405]])

In [31]:
print(i)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [32]:
print(x)

[[1 2]
 [2 3]
 [3 4]]


In [33]:
print(a)

[1, 2, 3]


In [34]:
#dot prodct of 2D array
v1= np.array([1,2,3])
v2= np.array([4,5,6])
dot_product=np.dot(v1,v2)
print(dot_product)

32
