In [12]:
import numpy as np

In [13]:
a=[1,2,3]

In [14]:
print(a)

[1, 2, 3]


In [15]:
#converting list to array
b=np.array(a)

In [16]:
print(b)

[1 2 3]


In [17]:
#sorting
print(b[1:3])

[2 3]


In [18]:
m=[1,2,]
n=[2,3,]
o=[3,4,]

In [19]:
#2D array
x=np.array([m,n,o])

In [20]:
print(x)

[[1 2]
 [2 3]
 [3 4]]


In [21]:
#finding shape of array
x.shape

(3, 2)

In [22]:
#changing shape of array rows to colums
x.reshape(2,3)

array([[1, 2, 2],
       [3, 3, 4]])

In [23]:
#random numbers
l=np.arange(1,19)

In [24]:
print(l)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [25]:
#changing 1D array to 2D array using reshape 
i=l.reshape(3,6)
print(i)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [26]:
#accessing elements using indexing
i[2,5]

np.int64(18)

In [27]:
#to know type of array
print(type(i))

<class 'numpy.ndarray'>


In [28]:
arr=np.array([[1,2,3],[2,3,4]])
print(arr)

[[1 2 3]
 [2 3 4]]


In [29]:
#sorting 2D array
print(arr[0:2,1:3])

[[2 3]
 [3 4]]


In [30]:
#reshapping 2D array
arr.reshape(3,2)

array([[1, 2],
       [3, 2],
       [3, 4]])

In [31]:
print(i)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [32]:
print(i[2:,:5])

[[13 14 15 16 17]]


In [33]:
print(i)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [34]:
i.shape

(3, 6)

In [35]:
i.reshape(6,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [36]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [37]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.random.randint(2,33,6).reshape(3,2)

array([[24, 23],
       [ 2, 12],
       [ 9, 19]], dtype=int32)

In [39]:
np.random.randn(3,3)

array([[-0.80947557,  0.79526329,  1.2858023 ],
       [-1.46343967,  0.5882277 , -0.95273931],
       [ 3.22138087, -0.44042634, -0.96658686]])

In [40]:
print(i)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [41]:
print(x)

[[1 2]
 [2 3]
 [3 4]]


In [42]:
print(a)

[1, 2, 3]


In [43]:
#dot prodct of 2D array
v1= np.array([1,2,3])
v2= np.array([4,5,6])
dot_product=np.dot(v1,v2)
print(dot_product)

32


In [44]:
identity_matrix = np.eye(3)  # Creates a 3x3 identity matrix
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [45]:
arr = np.array([[3, 6, 1], [8, 5, 2], [4, 9, 7]])

print("Max:", np.max(arr))       # Finds the maximum element
print("Min:", np.min(arr))       # Finds the minimum element
print("Sum:", np.sum(arr))       # Sums all elements
print("Column-wise Max:", np.max(arr, axis=0))  # Finds max along columns
print("Row-wise Min:", np.min(arr, axis=1))     # Finds min along rows


Max: 9
Min: 1
Sum: 45
Column-wise Max: [8 9 7]
Row-wise Min: [1 2 4]


In [46]:
random_floats = np.random.rand(3, 3)  # Generates a 3x3 matrix of random floats
print(random_floats)


[[1.52836340e-01 1.57722112e-01 6.22819607e-01]
 [7.11469792e-01 3.44820294e-01 6.19952379e-01]
 [5.81742817e-01 4.17584258e-01 5.72481305e-04]]


In [47]:
diag_matrix = np.diag([1, 2, 3, 4])  # Creates a diagonal matrix with given values
print(diag_matrix)


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [48]:
arr = np.array([1, 2, 2, 3, 4, 4, 5])
unique_vals = np.unique(arr)  # Finds unique elements in the array
print(unique_vals)


[1 2 3 4 5]


In [49]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Horizontal stacking (side-by-side)
h_stack = np.hstack((a, b))
print("Horizontally Stacked:\n", h_stack)

# Vertical stacking (top and bottom)
v_stack = np.vstack((a, b))
print("Vertically Stacked:\n", v_stack)


Horizontally Stacked:
 [[1 2 5 6]
 [3 4 7 8]]
Vertically Stacked:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [50]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Get elements greater than 5
filtered_arr = arr[arr > 5]
print(filtered_arr)


[6 7 8 9]


In [51]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Multiplication:", a * b)
print("Exponentiation:", np.exp(a))
print("Square Root:", np.sqrt(a))


Addition: [5 7 9]
Multiplication: [ 4 10 18]
Exponentiation: [ 2.71828183  7.3890561  20.08553692]
Square Root: [1.         1.41421356 1.73205081]


In [52]:
arr = np.array([10, 20, 30, 40, 50])

print("Mean:", np.mean(arr))          # Average value
print("Variance:", np.var(arr))       # Variance of elements
print("Standard Deviation:", np.std(arr))  # Standard deviation


Mean: 30.0
Variance: 200.0
Standard Deviation: 14.142135623730951


In [53]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
transposed_matrix = matrix.T  # Transposes the matrix
print(transposed_matrix)


[[1 4]
 [2 5]
 [3 6]]
